In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('./data/sample.csv')
df.head()

  created_date    borough channel complaint_type  response_time_days
0   2024-02-02     Queens     Web       Plumbing               18.27
1   2024-10-09  Manhattan   Phone       Plumbing                3.52
2   2024-08-26     Queens   Phone        Rodents                2.34
3   2024-06-09   Brooklyn     Web        Rodents                2.08
4   2024-06-07      Bronx     App       Plumbing                5.95

In [13]:
df['created_date'] = pd.to_datetime(df['created_date'], format='%Y-%m-%d')
df['created_date'].dtype

dtype('<M8[ns]')

In [38]:
df["channel"].value_counts()

channel
Web      321
Phone    175
App      104
Name: count, dtype: int64

In [33]:
app = df["channel"].value_counts().get('App',0)
total = len(df)
((app / total) * 100).round(2)

np.float64(17.333333333333336)

In [36]:
df.groupby("borough", as_index=False).size().reset_index()

   index        borough  size
0      0          Bronx    95
1      1       Brooklyn   172
2      2      Manhattan   136
3      3         Queens   157
4      4  Staten Island    40